add_newline = false

format = """
$jobs\
$directory\
$git_branch\
$git_state\
$git_status\
$status
$character
"""

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[x❯](bold red)"

[directory]
truncation_length = 6
truncation_symbol = "…/" 
truncate_to_repo = false 
style = "bold blue dimmed" 

[git_branch]
symbol = ""
style = "bold yellow dimmed"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_state]
style = "bold red dimmed"

[git_status]
format = '[$all_status$ahead_behind]($style)'
conflicted = '!' 
ahead = '↑'
behind = '↓'
modified = '✎' 
staged = '+'
untracked = '' 
diverged = ''
stashed = ''
up_to_date = ''
style = 'bold green dimmed'
