windowrulev2 = workspace $test_ws, class:^$test_brow$

# note toking
windowrulev2 = float, title:note_taking
windowrulev2 = float, title:pomodoro
windowrulev2 = size 50% 80%, title:note_taking
windowrulev2 = move 15% 10%, title:note_taking
windowrulev2 = size 20% 80%, title:pomodoro
windowrulev2 = move 65.1% 10%, title:pomodoro
