[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[window]]
name = "nvim"
startup_script = "nvim"

[[window]]
name = "opencode"
startup_script = "opencode"

[[window]]
name = "web"
startup_script = "cd web && nvim"

[[window]]
name = "backend"
startup_script = "cd backend && nvim"

[[window]]
name = "run"
startup_script = "cd ."

[[window]]
name = "command"
startup_script = "cd ."

[[window]]
name = "music"
startup_script = "cd ~/Documents/clasical && ranger"

# --- sessions ---
[[session]]
name = "default"
path = "~/"
startup_command = ""
windows = ["music","focus-read"]

[[session]]
name = "libam"
path = "~/projects/libam"
startup_command = "hyprctl dispatch exec '[workspace 6] firefox http://localhost:5173' & cd web & nvim"
windows = ["backend"]

[[session]]
name = "libam-command"
path = "~/projects/libam"
windows = ["command","run", "opencode"]

[[window]]
name = "epr"
startup_script = "epr \"The Gay Science - With a Prelude in Rhymes and an Appendix -- Friedrich Nietzsche, Bernard Williams, Josefine Nauckhoff, -- ( WeLib.org ).epub\""

[[window]]
name = "focus-read"
startup_script = "/home/yohansh/projects/focus_read"
