set -sg escape-time 0
set -g focus-events on
set -g history-limit 50000
set -g detach-on-destroy off
set -g automatic-rename on
set -g status-interval 3

unbind C-b
unbind x
set -g prefix C-Space
bind C-Space send-prefix
set -g prefix2 F12
bind F12 send-prefix -2

unbind "a"
unbind r
unbind n
unbind o
unbind e
unbind u
unbind i
unbind f
unbind [
bind "a" select-window -t 0
bind o select-window -t 1
bind e select-window -t 2
bind u select-window -t 3
bind i select-window -t 4
bind r command-prompt -I "#W" "rename-window -- '%%'"
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind K kill-session
bind n new-window
bind-key "f" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 90%,90% \ --no-sort --ansi --no-preview
)\""
bind Escape copy-mode
bind-key E capture-pane -S - -E - \; new-window -n "history" 'sh -c "tmux save-buffer - | nvim -c \"setlocal buftype=nofile bufhidden=hide noswapfile\" -"'
bind Enter split-window -h
bind-key h split-window -v
bind c kill-pane
bind Space select-pane -t :.+
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-no-clear
bind-key -T copy-mode-vi i send -X cancel


ACTIVE_COLOR="green"
INACTIVE_COLOR="blue-black"
TEXT_COLOR="magenta"

set -g status-style "bg=default,fg=$TEXT_COLOR"
set -g automatic-rename-format "\
#{?#{==:#{pane_current_command},fish},❯,\
#{?#{m:*nvim*,#{pane_current_command}},nvim,\
#{?#{m:*python*,#{pane_current_command}},py,\
#{?#{m:*docker*,#{pane_current_command}},docker,\
#{?#{m:*node*,#{pane_current_command}},node,\
#{?#{m:*git*,#{pane_current_command}},git,\
#{pane_current_command}}}}}}}"

# Only show window names when in prefix mode, otherwise show nothing
set -g window-status-format "#[fg=$INACTIVE_COLOR]#{?#{client_prefix}, #W,}"
set -g window-status-current-format "#[fg=$ACTIVE_COLOR,bold]#{?#{client_prefix}, #W,}"

set -g window-status-separator " "

set -g status-left "#{?client_prefix,#S ,}"
set -g status-right "#{?client_prefix,#{?@nvim_file_name,#[fg=$INACTIVE_COLOR] #{@nvim_file_name} #[fg=$INACTIVE_COLOR],}#{?VIRTUAL_ENV,#[fg=yellow] 󰌠 #[fg=$INACTIVE_COLOR]venv, },}"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
