set -sg escape-time 0
set -g focus-events on
set -g history-limit 50000
set -g detach-on-destroy off
set -g automatic-rename on
set -g status-interval 3
set -g prefix C-Space
set -g prefix2 F12
bind F12 send-prefix -2

set -g base-index 0
set -g renumber-window on

unbind C-b
unbind x
unbind "a"
unbind r
unbind n
unbind o
unbind e
unbind u
unbind i
unbind f
unbind [

bind "a" select-window -t 0
bind o select-window -t 1
bind e select-window -t 2
bind u select-window -t 3
bind i select-window -t 4
bind r command-prompt -I "#W" "rename-window -- '%%'"
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind K confirm-before kill-session
bind n new-window -c "#{pane_current_path}"
bind Enter split-window -h
bind-key h split-window -v
bind c confirm-before kill-pane
bind Space select-pane -t :.+
setw -g mode-keys vi

bind Escape copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-no-clear
bind-key -T copy-mode-vi i send -X cancel

bind-key E capture-pane -S - -E - \; new-window -n "history" 'sh -c "tmux save-buffer - | nvim -c \"setlocal buftype=nofile bufhidden=hide noswapfile\" -"'
bind-key C-n run-shell 'current_dir="#{pane_current_path}"; session_name=$(basename "$(dirname "$current_dir")")/$(basename "$current_dir"); tmux new-session -d -c "$current_dir" -s "$session_name" 2>/dev/null && tmux display-message "Created session: $session_name" || tmux display-message "Session $session_name already exists!"'
bind-key s choose-tree -ZsO time -F '#{}'

set -g automatic-rename-format "\
#{?#{m:*python*,#{pane_current_command}},py,\
#{?#{==:#{pane_current_command},fish},❯-,\
#{pane_current_command}}}"

set -g status-style "bg=default,fg=magenta"
set -g status-left "#S"
set -g status-right ""
set -g window-status-format "#[fg=blue-black] #W"
set -g window-status-separator " "

set -g window-status-current-format "#[fg=green,bold] #W"

# plugins
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
